config/routes.rb
Rails.application.routes.draw do
  root 'comments#index'
  
  devise_for :users
  
  resources :comments
  resources :properties

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: "User"
  belongs_to :property
end

app/models/property.rb
class Property < ApplicationRecord
  # belongs_to :owner
belongs_to :owner, class_name: "User"
has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :own_properties, class_name: "Property", foreign_key: "owner_id", dependent: :destroy

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: %i[ show edit update destroy ]

  # GET /comments or /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1 or /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new(property_id: params[:property_id])
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments or /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to comment_url(@comment), notice: "Comment was successfully created." }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1 or /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to comment_url(@comment), notice: "Comment was successfully updated." }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1 or /comments/1.json
  def destroy
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to comments_url, notice: "Comment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def comment_params
      params.require(:comment).permit(:body, :author_id, :property_id)
    end
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_action :set_property, only: %i[ show edit update destroy ]

  # GET /properties or /properties.json
  def index
    @properties = Property.all
  end

  # GET /properties/1 or /properties/1.json
  def show
  end

  # GET /properties/new
  def new
    @property = Property.new
  end

  # GET /properties/1/edit
  def edit
  end

  # POST /properties or /properties.json
  def create
    @property = Property.new(property_params)

    respond_to do |format|
      if @property.save
        format.html { redirect_to property_url(@property), notice: "Property was successfully created." }
        format.json { render :show, status: :created, location: @property }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /properties/1 or /properties/1.json
  def update
    respond_to do |format|
      if @property.update(property_params)
        format.html { redirect_to property_url(@property), notice: "Property was successfully updated." }
        format.json { render :show, status: :ok, location: @property }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /properties/1 or /properties/1.json
  def destroy
    @property.destroy

    respond_to do |format|
      format.html { redirect_to properties_url, notice: "Property was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_property
      @property = Property.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def property_params
      params.require(:property).permit(:caption, :image, :owner_id, :address, :bedrooms, :bathrooms, :rent, :mortgage, :tenant_name, :tenant_phone, :comments_count)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/views/comments/_form.html.erb
<%= form_with(model: comment) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
        <% comment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="field">
    <%= form.label :author_id %>
    <%= form.text_field :author_id %>
  </div>

  <div class="field">
    <%= form.label :property_id %>
    <%= form.text_field :property_id, value: @comment.property_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<%= render "properties/summary" %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<p>
  <strong>Author:</strong>
  <%= @comment.author_id %>
</p>

<p>
  <strong>Property:</strong>
  <%= @comment.property_id %>
</p>
<%= link_to 'Add Comment', new_comment_path%>
<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Managed!</title>
    
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= render "shared/cdn_assets" %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <div class="container">
    <%= yield %>
    </div>
  </body>
</html>

app/views/properties/_form.html.erb
<%= form_with(model: property, class: "form") do |form| %>
  <% if property.errors.any? %>
    <div class="alert alert-danger">
      <h2><%= pluralize(property.errors.count, "error") %> prohibited this property from being saved:</h2>

      <ul>
        <% property.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


<div class="form-group">
  <%= form.label :image %>
  <%= form.file_field :image, class: "form-control" %>
</div>

  <div class="form-group">
    <%= form.label :owner_id %>
    <%= form.text_field :owner_id, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :address %>
    <%= form.text_field :address, class: "form-control" %>
  </div>

  <div class="form-row">
    <div class="form-group col-md-6">
      <%= form.label :bedrooms %>
      <%= form.number_field :bedrooms, class: "form-control" %>
    </div>

    <div class="form-group col-md-6">
      <%= form.label :bathrooms %>
      <%= form.text_field :bathrooms, class: "form-control" %>
    </div>
  </div>

  <div class="form-row">
    <div class="form-group col-md-6">
      <%= form.label :rent %>
      <%= form.text_field :rent, class: "form-control" %>
    </div>

    <div class="form-group col-md-6">
      <%= form.label :mortgage %>
      <%= form.text_field :mortgage, class: "form-control" %>
    </div>
  </div>

  <div class="form-row">
    <div class="form-group col-md-6">
      <%= form.label :tenant_name %>
      <%= form.text_field :tenant_name, class: "form-control" %>
    </div>

    <div class="form-group col-md-6">
      <%= form.label :tenant_phone %>
      <%= form.text_field :tenant_phone, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= form.submit "Save", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/properties/_summary.html.erb
<div class="container my-5">
  <h1 class="text-center mb-5">Welcome to the Property Manager Dashboard</h1>
  
  <div class="row">
    <div class="col-md-6">
      <div class="card border-dark mb-4">
        <div class="card-body text-dark">
          <h5 class="card-title">Total number of properties</h5>
          <p class="card-text display-4"><%= Property.count %></p>
        </div>
      </div>
    </div>
    
    <div class="col-md-6">
      <div class="card border-dark mb-4">
        <div class="card-body text-dark">
          <h5 class="card-title">Total number of properties by owner</h5>
          <ul class="list-group">
            <% User.all.each do |owner| %>
              <li class="list-group-item">
              <%= owner.username %>: <%= owner.own_properties.count %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
    
    <div class="col-md-6">
      <div class="card border-dark mb-4">
        <div class="card-body text-dark">
          <h5 class="card-title">Total revenue generated from properties</h5>
          <p class="card-text display-4">$<%= number_with_delimiter(Property.sum(:rent)) %></p>
        </div>
      </div>
    </div>
    
    <div class="col-md-6">
      <div class="card border-dark mb-4">
        <div class="card-body text-dark">
          <h5 class="card-title">Number of vacant properties</h5>
          <p class="card-text display-4"><%= Property.where(tenant_name: nil).count %></p>
        </div>
      </div>
    </div>
  </div>
  
  <div class="row">
    <div class="col text-center">
      <%= link_to 'Manage your properties', properties_path, class: 'btn btn-lg btn-outline-dark' %>
    </div>
  </div>
</div>

app/views/properties/edit.html.erb
<h1>Editing Property</h1>

<%= render 'form', property: @property %>

<%= link_to 'Show', @property %> |
<%= link_to 'Back', properties_path %>

app/views/properties/index.html.erb
<p id="notice"><%= notice %></p>

  <div class="col-md-4">
    <%= form_tag properties_path, method: :get, class: "form-inline" do %>
      <label for="owner_username" class="mr-2">Owner:</label>
      <%= select_tag "owner_username", options_for_select(User.pluck(:username)), prompt: "Select owner", class: "form-control mr-2", onchange: "this.form.submit();" %>
    <% end %>
  </div>
  
<div class="row mb-3">
  <div class="col-md-4">
    <%= form_tag properties_path, method: :get, class: "form-inline" do %>
      <label for="bedrooms" class="mr-2">Bedrooms:</label>
      <%= select_tag "bedrooms", options_for_select((1..10).map { |n| [n, n] }), prompt: "Select bedrooms", class: "form-control mr-2", onchange: "this.form.submit();" %>
    <% end %>
  </div>

  <div class="col-md-4">
    <%= form_tag properties_path, method: :get, class: "form-inline" do %>
      <label for="bathrooms" class="mr-2">Bathrooms:</label>
      <%= select_tag "bathrooms", options_for_select((1..5).map { |n| [n, n] }), prompt: "Select bathrooms", class: "form-control mr-2", onchange: "this.form.submit();" %>
    <% end %>
  </div>
</div>

<h1>Properties</h1>
<table class="table table-dark table-striped">
  <thead>
    <tr>
      <th>Image</th>
      <th>Owner</th>
      <th>Address</th>
      <th>Bedrooms</th>
      <th>Bathrooms</th>
      <th>Rent</th>
      <th>Mortgage</th>
      <th>Tenant name</th>
      <th>Tenant phone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @properties.each do |property| %>
      <tr>
        <td><%= image_tag property.image %></td>
        <td><%= property.owner.username %></td>
        <td><%= property.address %></td>
        <td><%= property.bedrooms %></td>
        <td><%= property.bathrooms %></td>
        <td><%= property.rent %></td>
        <td><%= property.mortgage %></td>
        <td><%= property.tenant_name %></td>
        <td><%= property.tenant_phone %></td>
        <td><%= link_to 'Show', property %></td>
        <td><%= link_to 'Edit', edit_property_path(property) %></td>
        <td><%= link_to 'Destroy', property, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<br>
<div style="padding-left: 20px;">
<%= link_to 'New Property', new_property_path, class: "btn btn-primary", style: "padding-left: 5px;" %>
</div>

app/views/properties/new.html.erb
<h1>New Property</h1>

<%= render 'form', property: @property %>

<%= link_to 'Back', properties_path %>

app/views/properties/show.html.erb
<div class="container my-5">
  <div class="row">
    <div class="col-md-4">
      <img src="<%= @property.image %>" class="img-fluid rounded">
    </div>
    <div class="col-md-8">
      <h1><%= @property.address %></h1>
      <p class="lead">Owned by <%= @property.owner.username %></p>
      <hr>
      <h3>Details:</h3>
      <p><strong>Bedrooms:</strong> <%= @property.bedrooms %></p>
      <p><strong>Bathrooms:</strong> <%= @property.bathrooms %></p>
      <p><strong>Rent:</strong> <%= number_to_currency(@property.rent) %></p>
      <p><strong>Mortgage:</strong> <%= number_to_currency(@property.mortgage) %></p>
      <p><strong>Tenant name:</strong> <%= @property.tenant_name %></p>
      <p><strong>Tenant phone:</strong> <%= @property.tenant_phone %></p>
    </div>
  </div>
  <div class="row mt-5">
    <div class="col">
      <%= link_to 'Add Comment', new_comment_path, class: "btn btn-dark" %>
      <%= link_to 'Edit', edit_property_path(@property), class: "btn btn-secondary" %>
      <%= link_to 'Back', properties_path, class: "btn btn-light" %>
    </div>
  </div>
</div>

app/views/shared/_cdn_assets.html.erb
<!-- Expand the number of characters we can use in the document beyond basic ASCII 🎉 -->
<meta charset="utf-8">


<!-- Connect Bootstrap CSS -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

<!-- Connect Bootstrap JavaScript and its dependencies -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>

<!-- Connect Font Awesome -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/js/all.min

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to "Managed", root_path, class:  "navbar-brand"%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Options
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="/comments">Comments</a></li>
          </ul>
        </li>
      </ul>
      <ul class ="navbar-nav mr-auto">
      <% if user_signed_in? %>
              <li class="nav-item">
          <%= link_to "Edit Profile", edit_user_registration_path, class: "navbar-brand"%>
        </li>

        <li class="nav-item">
          <%#= button_to "Sign out", destroy_user_session_path, method: :delete, class: "navbar-brand"%>
          <%= button_to('Sign out', destroy_user_session_path, method: "delete", remote: true) %>
        </li>

      <% else %>
      <li class="nav-item">
        <%= link_to "Sign in", new_user_session_path, class: "navbar-brand"%>
        </li>

        <li class="nav-item">
          <%= link_to "Sign up", new_user_registration_path, class: "navbar-brand"%>
        </li>


      <% end %>

        


        
        
    </div>
  </div>
</nav>